#!/bin/sh

version="$1"

# passing the kernel version is required
[ -z "${version}" ] && exit 0

# avoid running multiple times
if [ -n "$DEB_MAINT_PARAMS" ]; then
	eval set -- "$DEB_MAINT_PARAMS"
	if [ -z "$1" ] || [ "$1" != "configure" ]; then
		exit 0
	fi
fi

echo "kernel-install: Removing kernel and loader entry for $version"
kernel-install remove "${version}" >&2
